### PR TITLE
Geospatial bugfixes

### PR DESCRIPTION
**Pull request by cliffckerr**
fixes several bugs in portfolio.py

### CODE REVIEW

**Comment by cliffckerr** [comment]
@robynstuart please review, bugs fixed

**Comment by robynstuart** [comment]
Export results sends results to excel with numbers stored as text. Can this be fixed?

**Comment by cliffckerr** [comment]
yes -- so it was a number represented as a string being stored as a number which actually stored it as a string. now it's a number represented as a number being stored as a number, which works.

**Comment by robynstuart** [comment]
Would also be great to have "Outcome" disaggregated into "Infections averted" and "Deaths averted" or "Cumulative infections" vs "Cumulative deaths" or any other more meaningful thing

**Comment by cliffckerr** [comment]
agreed

**Comment by robynstuart** [comment]
thanks @cliffckerr @davidkedz !!

**Pull request merged**
