### PR TITLE
Remove a potential divide by zero

### PR DESCRIPTION
**Pull request by Rowanmh**
... leading eventually to non-positive people error

### CODE REVIEW

**Comment by cliffckerr** [comment]
Actually @Rowanmh  looking at it more closely, if `trial_vec.sum()` is zero then there's no point doing this loop, so best just to terminate, no?

**Comment by ckerr-IDM** [comment]
@Rowanmh I'm still curious about the case that resulted in this error. It seems like it should only happen if you're trying to optimize a budget of $0. The error could be more helpful, but I do think it's appropriate to throw an error in that case :) Do you remember what caused this originally?

**Comment by Rowanmh** [comment]
@cliffk - this happened when running a money minimization with some aggressive but achievable targets near saturation

**Comment by cliffckerr** [comment]
@Rowanmh Really? I don't understand how the entire vector is 0 though...my feeling is there's probably a deeper bug here. If you're able to reproduce reliably (setting the random seed), would be good to debug further...

**Comment by cliffckerr** [comment]
Superseded by #1814

**Pull request closed without merging**
