### PR TITLE
feat(Calibration): fixing page height issue

### PR DESCRIPTION
**Pull request by jpuri**
This small change should fix page height issue on calibration page.

@cliffckerr , @guptaarun: can you plz review.

### CODE REVIEW

**Comment by jpuri** [comment]
I also added fix for this card to the PR: https://trello.com/c/nPWH398j/805-fixes-to-parameters-for-defining-cost-function-table-in-cost-function-page

**Comment by jpuri** [comment]
@robynstuart: can you plz review changes for tab-1.

**Comment by cliffckerr** [comment]
@jpuri can you make it so the page height applies to all elements, not just the graphs? e.g. the plot selector and manual fit editor as well

**Comment by cliffckerr** [comment]
nevermind, fixed

**Pull request merged**
