### PR TITLE
PRs 2019jul15

### PR DESCRIPTION
**Pull request by cliffckerr**
Includes the other 3 open PRs. Supposed to be 2019, not 2018...

### CODE REVIEW

**Comment by RomeshA** [comment]
@cliffckerr is this PR ready to merge/mergable?

**Comment by RomeshA** [comment]
This is not mergable, scenarios give this error:

```
2019-07-16 10:30:35,962 ERROR: Exception during request <Request 'http://127.0.0.1:9000/api/procedure' [POST]>: Traceback (most recent call last):
  File "/mnt/c/Users/romesh.abey/Desktop/projects/optima/server/webapp/dataio.py", line 315, in _report_exception
    return api_call(*args, **kwargs)
  File "/home/romesh/.conda/envs/hiv/lib/python3.7/site-packages/Flask_Login-0.4.1-py3.7.egg/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/romesh.abey/Desktop/projects/optima/server/api.py", line 148, in run_remote_procedure
    result = fn(*args, **kwargs)
  File "/mnt/c/Users/romesh.abey/Desktop/projects/optima/server/webapp/dataio.py", line 1499, in make_scenarios_graphs
    project.runscenarios(end=endYear) # Only change end year from default
  File "/mnt/c/Users/romesh.abey/Desktop/projects/optima/optima/project.py", line 651, in runscenarios
    if nruns>1: # Handle uncertainty
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by cliffckerr** [comment]
@RomeshA should be fixed

**Comment by cliffckerr** [comment]
@RomeshA Do you remember what the deal with this is? It seems like most of these commits are merged, but git says no...

**Comment by cliffckerr** [comment]
This PR is haunted, see https://github.com/optimamodel/optima/pull/1818

**Pull request closed without merging**
